### ISSUE TITLE
KoaWebMonetization spend function doesn't handle balance undefined

### ISSUE THREAD

**Issue by andywong418** [sharafian/koa-web-monetization#1]
At the moment only an error is thrown when (balance < price) but there is no error thrown when balance is not defined at all (undefined < Integer returns false so bypasses the check).

**Comment by sharafian** [comment]
Should be fixed in https://github.com/interledgerjs/koa-web-monetization/commit/6eb507d33771f88cb545b2f810750e5df7510d6d , are you still encountering the error?

**Comment by andywong418** [comment]
Yeah it's fixed just updated it!
